# @package _global_
repr_net:
  _target_: src.models.BWCFR
  name: bwcfr
  network_type: tnet
  alpha: 1.0
  ipm: wass                       # wass | mmd
  has_prop_net_cov: True
  q_trunc: 0.05

  tune_hparams: False
  tune_range: 100                  # number of trials for random search
  tune_type: choice
  hparams_grid:
    lr:
      - 0.001
      - 0.005
      - 0.01
    batch_size:
      - 32
      - 64
      - 128
    wd:
      - 0.0
      - 0.001
      - 0.01
      - 0.1
    dim_hid1_multiplier:
      - 1.0
      - 1.5
      - 2.0
    dim_hid2_multiplier:
      - 1.0
      - 1.5
      - 2.0
