# @package _global_
repr_net:
  dim_repr_multiplier: 0.8
  dim_hid1_multiplier: 1.5
  dim_hid2_multiplier: 1.0
  lr: 0.01
  wd: 0.1
  batch_size: 64
  weight_nn_lr: 0.01
  weight_nn_wd: 0.0
  dim_hid3_multiplier: 1.5
prop_net_repr:
  dim_hid1_multiplier: 1.5
  lr: 0.001
  wd: 0.1
  batch_size: 32
prop_net_cov:
  dim_hid1_multiplier: 1.0
  lr: 0.001
  wd: 0.1
  batch_size: 32
cnf_repr:
  dim_hid1_multiplier: 1.5
  lr: 0.01
  batch_size: 64
  count_bins: 10
  noise_std_X: 0.1
  noise_std_Y: 0.5
